# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:20

# Create and set the working directory.
WORKDIR /usr/moneyflo/index.js

# Copy package.json and package-lock.json.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .

# Expose the port the app runs on.
EXPOSE 3000

# Define the command to run the app.
CMD [ "npm", "start" ]
